import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import GlobalProvider from "@/context/Provider";
// import PageSpinner from "@/component/appui/PageSpinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <GlobalProvider> */}
            {/* <PageSpinner  /> */}
             {children}
        {/* </GlobalProvider> */}
        </body>
    </html>
  );
}
