export const SET_CONTEXT_LOADING = "SET_CONTEXT_LOADING";
export const SET_CONTEXT_SUCCESS = "SET_CONTEXT_SUCCESS";
export const SET_CONTEXT_FAIL = "SET_CONTEXT_FAIL";
export const DELETE_CONTEXT = "DELETE_CONTEXT";
export const SET_CONTEXT_CUSTOM = "SET_CONTEXT_CUSTOM";